server:
    port: 8081

spring:
    application:
        name: seckillProject
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seckillProject?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
        username: shuting
        password: 123456
    data:
        redis:
            host: localhost
            port: 6379
            database: 1
            lettuce:
                pool:
                    max-active: 10
                    max-idle: 5
                    min-idle: 0
                    max-wait: -1000ms
            timeout: 3000ms

mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.shuting.seckillproject.entity

logging:
    level:
        com.shuting.seckillproject.mapper: debug



